In [1]:
import numpy as np
coord = np.load("./data/train/coords/1AQ3_1_S.npy")
print(coord.shape)
print(coord)

(12, 7, 3)
[[[          nan           nan           nan]
  [  -8.00399971  -96.04000092   36.0909996 ]
  [  -8.77400017  -96.42900085   34.93999863]
  [  -8.25599957  -95.97399902   33.58499908]
  [  -6.91099977  -96.54100037   33.14699936]
  [  -7.04300022  -97.85900116   32.5929985 ]
  [  -5.954       -93.48999786   33.63000107]]

 [[  -5.88800001  -98.96399689   32.86600113]
  [  -4.66699982  -98.46199799   31.94799995]
  [  -4.85699987  -98.2539978    30.52400017]
  [  -3.6400001   -97.59700012   29.9090004 ]
  [  -2.2809999   -98.14299774   30.33099937]
  [  -1.95099998  -99.35900116   29.65399933]
  [  -1.92700005  -95.21900177   31.61499977]]

 [[  -2.17499995 -100.77700043   30.41300011]
  [  -0.97600001 -101.70600128   29.88699913]
  [   0.42199999 -101.34500122   30.08300018]
  [   1.28499997 -102.05500031   29.0529995 ]
  [   0.972      -101.64800262   27.61599922]
  [   1.903      -100.66500092   27.16500092]
  [  -0.76499999 -104.23300171   27.81500053]]

 [[   1.45099998 